spring.main.web-application-type=none
logging.level.org.springframework = debug
spring.main.allow-circular-references = false
com.sun.javafx.application.PlatformImpl#startup(Runnable)

spring.jpa.database-platform=com.cypods.dbupdater.SQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url = jdbc:sqlite:gebuddy.db
spring.datasource.driver-class-name = org.sqlite.JDBC