spring.application.name=pod

spring.main.web-application-type=none
logging.level.org.springframework = debug
spring.main.allow-circular-references = false
com.sun.javafx.application.PlatformImpl#startup(Runnable)

spring.jpa.database-platform=com.osrs.pod.database.SQLDialect
#spring.jpa.hibernate.ddl-auto=update   #Adds columns automatically in db when added in entity
spring.datasource.url=jdbc:sqlite:Cypods/src/main/resources/gebuddyResource.db
spring.datasource.driver-class-name = org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.leak-detection-threshold=5000

#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.idle-timeout=600000


#Logging sql
#
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG

