spring.main.web-application-type=none
logging.level.org.springframework = debug
spring.main.allow-circular-references = false
com.sun.javafx.application.PlatformImpl#startup(Runnable)
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR


#spring.jpa.database-platform=com.cypods.gebuddy.SQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.datasource.url = jdbc:sqlite:gebuddy.db
spring.datasource.driver-class-name = org.sqlite.JDBC

spring.datasource.username = admin
spring.datasource.password = admin
